# Testing tools configuration
[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
minversion = "6.0"
log_cli_level = "INFO"

# Formatting tools configuration
[tool.black]
line-length = 99
target-version = ["py38"]

[tool.isort]
line_length = 99
profile = "black"

# Linting tools configuration
[tool.flake8]
max-line-length = 99
max-doc-length = 99
max-complexity = 10
exclude = [".git", "__pycache__", ".tox", "build", "dist", "*.egg_info", "venv"]
select = ["E", "W", "F", "C", "N", "R", "D", "H"]
# Ignore D107 Missing docstring in __init__
ignore = ["D107"]
# D100, D101, D102, D103: Ignore missing docstrings in tests
per-file-ignores = ["tests/*:D100,D101,D102,D103,D104"]
docstring-convention = "google"

# Static analysis tools configuration
[tool.mypy]
pretty = true
python_version = "3.10"
mypy_path = "$MYPY_CONFIG_FILE_DIR/lib"

# Ignore 3rd party libraries that have typing issues
[[tool.mypy.overrides]]
module = ["charms.tls_certificates_interface.*"]
follow_imports = "silent"
