name: Promote Charm

on:
  workflow_dispatch:
    inputs:
      promotion:
        type: choice
        description: Channel to promote from
        options:
          - edge -> beta
          - beta -> candidate
          - candidate -> stable
      arch:
        type: choice
        description: Architecture
        options:
          - amd64
          - arm64

env:
  PROMOTE_FROM: ${{ inputs.promotion == 'edge -> beta' && 'edge' || inputs.promotion == 'beta -> candidate' && 'beta' || inputs.promotion == 'candidate -> stable' && 'candidate' || '' }}
  PROMOTE_TO:   ${{ inputs.promotion == 'edge -> beta' && 'beta' || inputs.promotion == 'beta -> candidate' && 'candidate' || inputs.promotion == 'candidate -> stable' && 'stable' || '' }}
  PROMOTE_ARCH: ${{ inputs.arch }}

jobs:
  scan:
    name: Secscan
    uses: ./.github/workflows/secscan.yaml
    with:
      # We have to compute the channel here again because we can't pass env variables to a reusable workflow
      channel: ${{ inputs.promotion == 'edge -> beta' && 'edge' || inputs.promotion == 'beta -> candidate' && 'beta' || inputs.promotion == 'candidate -> stable' && 'candidate' || '' }}
      arch: ${{ inputs.arch }}
      create-issue: ${{ inputs.promotion == 'candidate -> stable' || inputs.promotion == 'beta -> candidate' }}

  promote:
    name: Promote Charm
    needs:
      - scan
    if: ${{ (inputs.promotion != 'candidate -> stable') || needs.scan.outputs.secscan-return-code == '0' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Promote Charm
        uses: canonical/charming-actions/release-charm@2.7.0
        with:
          credentials: ${{ secrets.CHARMCRAFT_AUTH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          destination-channel: 1/${{ env.PROMOTE_TO }}
          origin-channel: 1/${{ env.PROMOTE_FROM }}
          charmcraft-channel: latest/stable
          base-channel: "24.04"
          base-architecture: ${{ env.PROMOTE_ARCH }}
